version: '3'
services:
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: password
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ../memorize:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - "db"
    tty: true
